services:
  cdasim:
    privileged: true
    image: usdotfhwastolcandidate/cdasim:vantage
    networks:
      carma_sim_net:
        ipv4_address: 172.2.0.2
      carma_net_1:
        ipv4_address: 172.3.0.3
      carma_messenger_net_1:
        ipv4_address: 172.7.0.3
    container_name: cdasim
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /opt/carma-simulation/logs:/opt/carma-simulation/logs
      - ./cdasim/scenario_config.json/:/opt/carma-simulation/scenarios/Town10/scenario_config.json
      - ./cdasim/sumo/Town10.sumocfg:/opt/carma-simulation/scenarios/Town10/sumo/Town10.sumocfg
    group_add:
      - "998"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: bash -c "./mosaic.sh -s Town10"

###########################################################################
  platform_ros2_1:
    image: usdotfhwastol/carma-platform:carma-system-4.10.0
    networks:
      carma_net_1:
        ipv4_address: 172.3.0.4
    container_name: platform_ros2_1
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/carma/logs/carma_1:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
      - /opt/carma/maps:/opt/carma/maps
      - /opt/carma/routes:/opt/carma/routes
      - /opt/carma/yolo:/opt/carma/yolo
      # ILC tuning for carma-cloud workzone (carma_2) is breaking k900 normal lanefolow regression testing, so using different tuning
      - ./carma/inlanecruising_config/parameters.yaml:/opt/carma/install/inlanecruising_plugin/share/inlanecruising_plugin/config/parameters.yaml
      # - ./carma/environment.launch.py:/opt/carma/install/carma/share/carma/launch/environment.launch.py
      # - ./carma/light_controlled_intersection_tactical_plugin/parameters.yaml:/opt/carma/install/light_controlled_intersection_tactical_plugin/share/light_controlled_intersection_tactical_plugin/confi>
      # - ./carma/lci_strategic_plugin/parameters.yaml:/opt/carma/install/lci_strategic_plugin/share/lci_strategic_plugin/config/parameters.yaml
      # - ./carma/plugins.launch.py:/opt/carma/install/carma/share/carma/launch/plugins.launch.py
      - ./carma/system_controller/config.yaml:/opt/carma/install/system_controller/share/system_controller/config/config.yaml
      - ./carma/cooperative_lanechange/parameters.yaml:/opt/carma/install/cooperative_lanechange/share/cooperative_lanechange/config/parameters.yaml
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: bash -c 'export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
                      && source /opt/carma/install/setup.bash
                      && ros2 launch /opt/carma/vehicle/config/carma_docker.launch.py'


  carma-carla-integration_1:
    image: usdotfhwastolcandidate/carma-carla-integration:vantage
    networks:
      carma_net_1:
        ipv4_address: 172.3.0.6
      carma_sim_net:
        ipv4_address: 172.2.0.6
    container_name: carma-carla-integration_1
    volumes_from:
      - container:carma-config:ro
    depends_on:
      - cdasim
    environment:
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}
      ROS_DOMAIN_ID: 0
      ROS_LOCALHOST_ONLY: 0
    # sleep is for carla simulator to become available
    # start_delay_in_seconds is carla game time seconds to adjust when to engage for the scenario
    # and account for delay required for world model to fully update after route is selected
    command: >
      bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      && source /home/carma/carma-carla-integration/install/setup.bash
      && python3 /home/carma/carma-carla-integration/carla-health-poll/src/wait_for_carla.py --carla-host=carla-server
      && ros2 launch carma_carla_bridge carma_carla_bridge.launch.py
      role_name:='carma_1'
      host:='carla-server'
      synchronous_mode:=True
      selected_route:='Town10_loop_official'
      selected_plugins:='/guidance/plugins/route_following_plugin,/guidance/plugins/cooperative_lanechange,/guidance/plugins/inlanecruising_plugin,/guidance/plugins/stop_and_wait_plugin,/guidance/plugins/pure_pursuit_wrapper'
      start_delay_in_seconds:=30.0
      fixed_delay_seconds:=0.1
      passive:=True
      spawn_point:='58.6,133.5,0,0,0,180'"

  vehicle_registration_service:
  # the ns3 image here is built from https://github.com/usdot-fhwa-stol/carma-ns3-adapter/tree/feature/vehicle-registration-module
    image: usdotfhwastolcandidate/carma-ns3-adapter:vantage
    networks:
      carma_net_1:
        ipv4_address: 172.3.0.14
    container_name: vehicle_registration_service
    volumes_from:
      - container:carma-config:ro
    command: >
      bash -c 'python3 /opt/carma/vehicle-registration-module/src/vehicleRegistration.py --vehicleId "carma_1" --roleId "carma_1" \
               --rxMessageIpAddress 172.3.0.7 --rxMessagePort 2500 --rxTimeSyncPort 2501 --receiverPort 1515 --receiverIpAddress 172.3.0.3'


  v2x_ros_driver:
    image: usdotfhwastol/v2x-ros-driver:carma-system-4.11.0
    networks:
      carma_net_1:
        ipv4_address: 172.3.0.7
    container_name: v2x_ros_driver
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - ./carma/v2x_ros_driver/params.yaml:/opt/carma/install/v2x_ros_driver/share/v2x_ros_driver/config/params.yaml
    volumes_from:
      - container:carma-config:ro
    command: >
      bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && source /opt/carma/install/setup.bash && ros2 launch /opt/carma/vehicle/config/drivers.launch.py drivers:=v2x_ros_driver log_level:=DEBUG"

  xml_rpc_server:
    image: usdotfhwastol/xml-rpc-server:latest
    networks:
      carma_sim_net:
        ipv4_address: 172.2.0.12
    container_name: xml_rpc_server
    volumes_from:
      - container:carma-config:ro
    command:
      ["python3.10", "/home/carma/src/carla_v0.10_xmlrpc_server.py", "--debug", "--carla-host=carla-server", "--host=172.2.0.12"]
#############################################################################
#############################################################################
# carma messenger
  messenger_ros2_1:
    image: usdotfhwastol/carma-messenger-core:carma-system-4.10.0
    networks:
      carma_messenger_net_1:
        ipv4_address: 172.7.0.2
    container_name: messenger_ros2_1
    volumes_from:
      - container:carma-config:ro
    environment:
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}
    volumes:
      - /opt/carma-messenger/messenger_1/logs:/opt/carma/logs
      - /opt/carma-messenger/messenger_1/.ros:/home/carma/.ros
      - /opt/carma-messenger/messenger_1/routes:/opt/carma/routes
      - ./carma_messenger/vehicle/calibration:/opt/carma/vehicle/calibration
      - ./carma_messenger/traffic_incident/config:/opt/carma/install/traffic_incident/share/traffic_incident/config
    command: >
      bash -c "export RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION} && source /opt/carma/install/setup.bash
      && echo $RMW_IMPLEMENTATION && ros2 launch /opt/carma/vehicle/config/carma-messenger-docker.launch.py"

  carma_messenger_bridge_1:
    image: usdotfhwastol/carma-messenger-bridge:carma-system-4.9.0
    networks:
      carma_messenger_net_1:
        ipv4_address: 172.7.0.5
    volumes:
      - ./carma_messenger:/opt/mockns3
    environment:
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}
    container_name: carma_messenger_bridge_1
    command:
      bash -c 'export RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
      && source /home/carma/install/setup.bash
      && ros2 launch msger_mosaic_bridge mosaic_adapter_launch.py
      role_id:=msger_1
      messenger_ip_address:=172.7.0.2
      cdasim_ip_address:=172.7.0.3
      host_ip_address:=172.7.0.5'

  messenger_v2x_ros_driver:
    image: usdotfhwastol/v2x-ros-driver:carma-system-4.11.0
    networks:
      carma_messenger_net_1:
        ipv4_address: 172.7.0.6
    container_name: messenger_v2x_ros_driver
    volumes_from:
      - container:carma-config:ro
    environment:
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - ./carma_messenger/v2x_ros_driver/params.yaml:/opt/carma/install/v2x_ros_driver/share/v2x_ros_driver/config/params.yaml
    command: >
      bash -c "export RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION} && source /opt/carma/install/setup.bash && ros2 launch /opt/carma/vehicle/config/msger_drivers.launch.py log_level:=DEBUG"

  messenger_vehicle_registration_service:
  # the ns3 image here is built from https://github.com/usdot-fhwa-stol/carma-ns3-adapter/tree/feature/vehicle-registration-module
    image: usdotfhwastolcandidate/carma-ns3-adapter:vantage
    networks:
      carma_messenger_net_1:
        ipv4_address: 172.7.0.16
    container_name: messenger_vehicle_registration_service
    volumes_from:
      - container:carma-config:ro
    command: >
      bash -c 'python3 /opt/carma/vehicle-registration-module/src/vehicleRegistration.py --vehicleId "msger_1" --roleId "msger_1" \
               --rxMessageIpAddress 172.7.0.6 --rxMessagePort 3501 --rxTimeSyncPort 3500 --receiverPort 3600 --receiverIpAddress 172.7.0.3'

  carma-messenger-vehicle-plugin_1:
    image: usdotfhwastolcandidate/cdasim:vantage
    networks:
      carma_sim_net:
        ipv4_address: 172.2.0.11
    container_name: carma-messenger-vehilce-plugin_1
    volumes:
      - ./carma_messenger/logs:/home/carma/src/carma_messenger_vehicle_plugin/logs
      - ./carma_messenger/resources:/home/carma/src/carma_messenger_vehicle_plugin/src/resources
    command: bash -c "cd /home/carma/src/carma_messenger_vehicle_plugin/src && python3 msger_veh_wrapper.py --traci-ip 172.2.0.2 --traci-order-num 3"

#############################################################################
  carma-cloud:
    image: usdotfhwastol/carma-cloud:carma-system-4.6.1
    networks:
      carma_cloud_1:
        ipv4_address: 172.6.0.47
      carma_sim_net:
        ipv4_address: 172.2.0.47
    container_name: carma-cloud
    depends_on:
      - cdasim
    volumes:
      - ./carmacloudvol/logs:/opt/tomcat/logs
      - ./carmacloudvol/work:/opt/tomcat/work
      - ./carmacloudvol/web.xml:/opt/tomcat/webapps/carmacloud/ROOT/WEB-INF/web.xml
      - ./carmacloudvol/log4j2.properties:/opt/tomcat/webapps/carmacloud/WEB-INF/classes/log4j2.properties
    command: bash -c "/opt/tomcat/bin/catalina.sh run"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      carma_streets_net_1:
        ipv4_address: 172.4.0.3
    volumes:
      - zookeeper-datavolume:/opt/zookeeper-3.4.13/data

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    network_mode: service:zookeeper
    # Health check to confirm kafka server is healthy (script is a client) and all topics
    # have been created (time_sync is last topic).
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--describe", "--bootstrap-server", "172.4.0.3:9092", "--topic", "time_sync"]
      interval: 2s
      timeout: 10s
      retries: 10
    environment:
      DOCKER_HOST_IP: 172.4.0.3
      KAFKA_ADVERTISED_HOST_NAME: 172.4.0.3
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "\
        v2xhub_scheduling_plan_sub:1:1,\
        v2xhub_bsm_in:1:1,\
        v2xhub_mobility_operation_in:1:1,\
        v2xhub_mobility_path_in:1:1,\
        vehicle_status_intent_output:1:1,\
        v2xhub_map_msg_in:1:1,\
        modified_spat:1:1,\
        desired_phase_plan:1:1,\
        tsc_config_state:1:1,\
        v2xhub_sim_sensor_detected_object:1:1,\
        v2xhub_sdsm_sub,\
        time_sync:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka-datavolume:/kafka/kafka-logs

  # ##############################################################
  # # Kafka Owl for monitoring kafka traffic. UI can be accessed on
  # # configurable port set in performance/kowl.yaml NOTE: IS NOT
  # # NECESSARY FOR DEPLOYMENT BUT HELFUL FOR DEBUGGING!
  # ################################################################
  kowl:
    image: quay.io/cloudhut/kowl
    container_name: kowl
    restart: on-failure
    network_mode: service:zookeeper
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      CONFIG_FILEPATH: /etc/kowl/kowl.yaml
    volumes:
      - ./kowl:/etc/kowl/

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=IVP
      - MYSQL_USER=IVP
      - MYSQL_PASSWORD_FILE=/secrets/mysql_password.txt
      - MYSQL_ROOT_PASSWORD_FILE=/secrets/mysql_root_password.txt
    networks:
      carma_streets_net_1:
        ipv4_address: 172.4.0.2
      carma_sim_net:
        ipv4_address: 172.2.0.8
    volumes:
      - mysql-datavolume:/var/lib/mysql
      - ./secrets:/secrets
      - ./mysql:/docker-entrypoint-initdb.d

  php:
    image: usdotfhwaops/php:7.7.0
    container_name: php
    network_mode: service:db
    depends_on:
      - v2xhub
    stdin_open: true
    tty: true

  v2xhub:
    image: usdotfhwaops/v2xhub:7.7.0
    container_name: v2xhub
    network_mode: service:db
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_PASSWORD: /home/V2X-Hub/secrets/mysql_password.txt
      SIMULATION_MODE: ${SIMULATION_MODE}
      SIMULATION_IP: 172.2.0.2
      SIMULATION_REGISTRATION_PORT: 1615
      LOCAL_IP: 172.2.0.8
      TIME_SYNC_TOPIC: time_sync
      TIME_SYNC_PORT: 7575
      SIM_V2X_PORT: 1517
      SIM_INTERACTION_PORT: 7576
      V2X_PORT: 8686
      SENSOR_JSON_FILE_PATH: /home/V2X-Hub/sensor_configurations/sensors.json
      INFRASTRUCTURE_ID: ${INFRASTRUCTURE_ID}
    volumes:
      - ./logs:/var/log/tmx
      - ./MAP:/var/www/plugins/MAP
      - ./secrets:/home/V2X-Hub/secrets
      - ./sensor_configurations:/home/V2X-Hub/sensor_configurations/

  intersection_model:
    image: usdotfhwastol/intersection_model:carma-system-4.5.0
    container_name: intersection_model
    restart: always
    network_mode: service:zookeeper
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      DOCKER_HOST_IP: 172.4.0.3
    volumes:
      - ./intersection_model/manifest.json:/home/carma-streets/intersection_model/manifest.json
      - ./intersection_model/logs:/home/carma-streets/intersection_model/logs
      - ./MAP:/home/carma-streets/intersection_model/MAP

  carla-sensor-lib:
    image: usdotfhwastolcandidate/carla-sensor-lib:vantage
    networks:
      carma_sim_net:
        ipv4_address: 172.2.0.5
    container_name: carla-sensor-lib
    restart: always
    volumes:
      - ./carla-sensor-lib/logs/:/home/CarlaCDASimAdapter/logs/
    command: bash -c "sleep 8;  python3 -u /home/CarlaCDASimAdapter/src/CarlaCDASimAdapter.py --carla-host carla-server --xmlrpc-server-host 172.2.0.5 --xmlrpc-server-port 8091"
 
  tsc_service:
    image: usdotfhwastol/tsc_service:carma-system-4.5.1
    container_name: tsc_service
    restart: always
    network_mode: service:zookeeper
    depends_on:
      kafka:
        condition: service_healthy
      # Every dependency describe with this notation needs a condition
      # Condition service_started is the default for - notation
      # TODO: Replace docker-compose-wait with intersection_model health check
      intersection_model:
        condition: service_started
    environment:
      DOCKER_HOST_IP: 172.4.0.3
      WAIT_HOSTS: 127.0.0.1:8080
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 10
      WAIT_HOST_CONNECT_TIMEOUT: 30
      SIMULATION_MODE: ${SIMULATION_MODE}
      TIME_SYNC_TOPIC: time_sync
      CONFIG_FILE_PATH: /home/carma-streets/tsc_client_service/manifest.json
      LOGS_DIRECTORY: /home/carma-streets/tsc_client_service/logs/
    volumes:
      - ./tsc_client_service/manifest.json:/home/carma-streets/tsc_client_service/manifest.json
      - ./tsc_client_service/logs/:/home/carma-streets/tsc_client_service/logs/
    command: >
      sh -c "/wait
      && /home/carma-streets/tsc_client_service/build/traffic_signal_controller_service"

  sensor_data_sharing_service:
    image: usdotfhwastol/sensor_data_sharing_service:carma-system-4.5.0
    build:
      context: .
      dockerfile: sensor_data_sharing_service/Dockerfile
    container_name: sensor_data_sharing_service
    restart: always
    network_mode: service:zookeeper
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      SIMULATION_MODE: ${SIMULATION_MODE}
      CONFIG_FILE_PATH: /home/carma-streets/sensor_data_sharing_service/manifest.json
      TIME_SYNC_TOPIC: ${TIME_SYNC_TOPIC}
      LOGS_DIRECTORY: /home/carma-streets/sensor_data_sharing_service/logs/
      LANELET2_MAP: /home/carma-streets/MAP/Town10_vector_map.osm
      INFRASTRUCTURE_ID: ${INFRASTRUCTURE_ID}
      SENSOR_JSON_FILE_PATH: /home/carma-streets/sensor_configurations/sensors.json
    volumes:
      - ./sensor_data_sharing_service/manifest.json:/home/carma-streets/sensor_data_sharing_service/manifest.json
      - ./sensor_data_sharing_service/logs/:/home/carma-streets/sensor_data_sharing_service/logs/
      - ./MAP/:/home/carma-streets/MAP/
      - ./sensor_configurations/:/home/carma-streets/sensor_configurations/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  econolite-virtual-controller:
    image: usdotfhwastol/econolite-virtual-controller:latest
    container_name: evc
    restart: always
    networks:
      carma_sim_net:
        ipv4_address: 172.2.0.4
      carma_streets_net_1:
        ipv4_address: 172.4.0.4
    environment:
      - DISPLAY=${DISPLAY}
      - EVC_PORT_1=1515
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./evc_sumo/:/home/carma/src/resources/
      - ./PyEOS/:/home/carma/PyEOS
      - pyeos_data:/home/carma/shared_data
    depends_on:
      - cdasim
    # The socat command is for addressing Jira Bug TT-182 with the EVC
    command: >
      bash -c "socat UDP-LISTEN:1515,fork UDP:127.0.0.1:1515 & \
               cd /home/carma/docker && ./start_evc.sh --traci-ip 172.2.0.2"


networks:
  carma_sim_net:
    ipam:
      config:
        - subnet: 172.2.0.0/16

  carma_net_1:
    ipam:
      config:
        - subnet: 172.3.0.0/16

  carma_streets_net_1:
    ipam:
      config:
        - subnet: 172.4.0.0/16

  carma_net_2:
    ipam:
      config:
        - subnet: 172.5.0.0/16

  carma_cloud_1:
    ipam:
      config:
        - subnet: 172.6.0.0/16

  carma_messenger_net_1:
    ipam:
      config:
        - subnet: 172.7.0.0/16

volumes:
  mysql-datavolume:
  kafka-datavolume:
  zookeeper-datavolume:
  pyeos_data:
