version: '2'
services:
  web-ui:
    image: ${DOCKER_ORG}/carma-web-ui:${DOCKER_TAG}-humble
    container_name: web-ui
    network_mode: host
    volumes_from:
      - container:carma-config:ro
    environment:
      ROS_IP: 172.3.0.9
      ROS_MASTER_URI: http://172.3.0.2:11311/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
