services:
  carla:
    image: carlasim/carla:0.10.0
    container_name: cdasim
    network_mode: host
    environment:
        - DISPLAY=${DISPLAY}
        - QT_X11_NO_MITSHM=1
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /opt/carma-simulation/logs:/opt/carma-simulation/logs
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
    command: bash -c "./CarlaUnreal.sh"
      
  platform_ros2_1:
      image: usdotfhwastol/carma-platform:carma-system-4.11.0
      container_name: platform_ros2_1
      network_mode: host
      volumes_from:
      - container:carma-config:ro
      environment:
        - DISPLAY=${DISPLAY}
        - QT_X11_NO_MITSHM=1
        - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
        - ROS_DOMAIN_ID=0
        - ROS_LOCALHOST_ONLY=0
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /opt/carma/logs/carma_1:/opt/carma/logs
        - /opt/carma/.ros:/home/carma/.ros
        - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
        - /opt/carma/maps:/opt/carma/maps
        - /opt/carma/routes:/opt/carma/routes
        - /opt/carma/yolo:/opt/carma/yolo
        # ILC tuning for carma-cloud workzone (carma_2) is breaking k900 normal lanefolow regression testing, so using different tuning
        - ./carma/inlanecruising_config/parameters.yaml:/opt/carma/install/inlanecruising_plugin/share/inlanecruising_plugin/config/parameters.yaml
        # - ./carma/environment.launch.py:/opt/carma/install/carma/share/carma/launch/environment.launch.py
        # - ./carma/light_controlled_intersection_tactical_plugin/parameters.yaml:/opt/carma/install/light_controlled_intersection_tactical_plugin/share/light_controlled_intersection_tactical_plugin/confi>
        # - ./carma/lci_strategic_plugin/parameters.yaml:/opt/carma/install/lci_strategic_plugin/share/lci_strategic_plugin/config/parameters.yaml
        # - ./carma/plugins.launch.py:/opt/carma/install/carma/share/carma/launch/plugins.launch.py
        - ./carma/system_controller/config.yaml:/opt/carma/install/system_controller/share/system_controller/config/config.yaml
        - ./carma/cooperative_lanechange/parameters.yaml:/opt/carma/install/cooperative_lanechange/share/cooperative_lanechange/config/parameters.yaml
      deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
      command: bash -c 'export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
                        && source /opt/carma/install/setup.bash
                        && ros2 launch /opt/carma/vehicle/config/carma_docker.launch.py'

  carma-carla-integration_1:
    image: usdotfhwastoldev/carma-carla-integration:develop
    container_name: carma-carla-integration_1
    network_mode: host
    depends_on:
      - carla
    command: >
      bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      && source /home/carma/carma-carla-integration/install/setup.bash
      && python3 /home/carma/carma-carla-integration/carla-health-poll/src/wait_for_carla.py --carla-host=localhost
      && ros2 launch carma_carla_bridge carma_carla_bridge.launch.py
      role_name:='carma_1'
      host:='localhost'
      selected_route:='Town10_3way_route'
      selected_plugins:='/guidance/plugins/route_following_plugin,/guidance/plugins/cooperative_lanechange,/guidance/plugins/inlanecruising_plugin,/guidance/plugins/stop_and_wait_plugin,/guidance/plugins/pure_pursuit_wrapper'
      start_delay_in_seconds:=500.0
      fixed_delay_seconds:=20.0
      passive:=True
      demo_restart_count:=50
      spawn_point:='98.44,119.2,0,0,0,300'"

  v2x_ros_driver:
    image: usdotfhwastol/v2x-ros-driver:carma-system-4.11.0
    container_name: v2x_ros_driver
    network_mode: host
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - ./carma/v2x_ros_driver/params.yaml:/opt/carma/install/v2x_ros_driver/share/v2x_ros_driver/config/params.yaml
    command: >
      bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && source /opt/carma/install/setup.bash && ros2 launch /opt/carma/vehicle/config/drivers.launch.py drivers:=v2x_ros_driver log_level:=DEBUG"

  
  scenario-runner:
    image: usdotfhwastoldev/scenario-runner:develop
    container_name: scenario-runner
    network_mode: host
    depends_on:
      - carla
    volumes:
      - ../scenario-runner/trb_2027.py:/app/scenario_runner/srunner/scenarios/trb_2027.py
      - ../scenario-runner/trb_2027.xml:/app/scenario_runner/srunner/examples/trb_2027.xml
    # sleep is for mainly carma-platform's components to
    # activate and be ready before scenario starts
    entrypoint: >
      bash -c "sleep 30
      && python3 scenario_runner.py
      --scenario 'Trb2027_1'
      --host localhost"