name: Publish Docker Compose
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
      - "release/**"
      - "feature/**"
    tags:
      - "*"

jobs:
  publish-docker-compose:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (Xil_Messenger)
        id: meta_messenger
        uses: docker/metadata-action@v5
        with:
          images: usdotfhwastoldev/xil-messenger-application
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Publish Docker Compose (Xil_Messenger)
        run: |
          cd xil_carma_messenger
          docker compose publish --with-env --yes ${{ steps.meta_messenger.outputs.tags }}


      - name: Extract metadata (xil_carma_cloud)
        id: meta_cloud
        uses: docker/metadata-action@v5
        with:
          images: usdotfhwastoldev/xil-carma-cloud-application
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Publish Docker Compose (xil_carma_cloud)
        run: |
          cd xil_carma_cloud
          docker compose publish --with-env --yes ${{ steps.meta_cloud.outputs.tags }}